languageCode = "pt-pt"
languageName = "Português (Portugal)"
weight = 5
title = "Blowfish"

[params]
  displayName = "Português (Portugal)"
  isoCode = "pt-pt"
  rtl = false
  dateFormat = "2 de January de 2006"
  logo = ""
  disableTextInHeader = true
  description = ""

[params.author]
  name = "Blowfish"
  image = "img/blowfish_logo.png"
  headline = ""
  bio = ""
  links = []
