languageCode = "en"
languageName = "English"
weight = 1
title = "Blowfish"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = ""
  disableTextInHeader = true
  description = ""

[params.author]
  name = "Blowfish"
  email = "nuno@n9o.xyz"
  image = "img/blowfish_logo.png"
  headline = ""
  bio = ""
  links = []